const HOME_SCREEN = 'HOME_SCREEN';
const SETTINGS_SCREEN = 'SETTINGS_SCREEN';
const HOME_TAB = 'HOME_TAB';
const SETTINGS_TAB = 'SETTINGS_TAB';

export {HOME_SCREEN, SETTINGS_SCREEN, HOME_TAB, SETTINGS_TAB};
